### PR TITLE
Add --deactivate-only option to environment:delete.

### PR DESCRIPTION
**Pull request by vincenzo**
This is trying to address an issue I raised myself (https://github.com/platformsh/platformsh-cli/issues/357) by adding an extra option to the `environment:delete` command.

### CODE REVIEW

**Comment by pjcdawkins** [comment]
I made a PR around the same time you did (#361), adding a `--delete-branch` option (with a default to leave the branch there).

**Comment by vincenzo** [comment]
Ha. ;)
Let's go with yours then.

**Comment by pjcdawkins** [comment]
Thanks anyway!

**Comment by vincenzo** [comment]
My pleasure. You're gonna get more from me. Got a few things to work on.

**Comment by GuGuss** [comment]
:+1:

**Pull request closed without merging**
