### PR TITLE
Adding more precise dbsize

### PR DESCRIPTION
**Pull request by matthiaz**
And some refactoring

### CODE REVIEW

**Comment by pjcdawkins** [comment]
https://github.com/matthiaz/platformsh-cli/pull/1

**Comment by pjcdawkins** [comment]
It seems the column `ALLOCATED_SIZE` doesn't exist in `information_schema.innodb_sys_tablespaces` for older MariaDB versions (works in 10.2, doesn't work in 10.0). We need to test for the existence of that column.

**Comment by matthiaz** [comment]
> It seems the column `ALLOCATED_SIZE` doesn't exist in `information_schema.innodb_sys_tablespaces` for older MariaDB versions (works in 10.2, doesn't work in 10.0). We need to test for the existence of that column.

I fixed that.

**Comment by matthiaz** [comment]
I also expanded on the 'cleanup' option
so you can do something like `platform db:size -p 3oupdxcaenytw -e master -r database1 --cleanup`

InnoDB does not automatically clean up deleted data, but running an ALTER TABLE Engine forces it to be recreated. 

--cleanup won't do this without first asking confirmation from the user.

**Pull request merged**
